version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grocery_db
    ports:
      - "3306:3306"
  app:
    build: .
    container_name: grocery-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: Vishal@123
      DB_NAME: testdb
    depends_on:
      - db
